branch-defaults:
  default:
    environment: UnicahAppApi-env
  master:
    environment: UnicahAppApi-env
environment-defaults:
  UnicahAppApi-env:
    branch: null
    repository: null
global:
  application_name: unicah_app_api
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.7.1
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
